volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/qtay/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/qtay/data/mariadb
                        o: bind
                        type: none

networks:
    inception:
        name: inception
        driver: bridge

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/html
        ports:
            - 443:443
        networks:
            - inception
        restart: always

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        env_file:
            - .env
        restart:
            always

    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
        env_file:
            - .env
        restart:
            always